version: "3.8"

services:
  producer:
    build:
      dockerfile: Dockerfile
      context: ./
      target: dev
    command: CompileDaemon -directory="./" -build="go build -o ./bin/producer ./cmd/producer/main.go ./cmd/producer/wire_gen.go ./cmd/producer/router.go" -command="./bin/producer" -polling=true -polling-interval=600
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
  consumer:
    build:
      dockerfile: Dockerfile
      context: ./
      target: dev
    command: CompileDaemon -directory="./" -build="go build -o ./bin/consumer ./cmd/consumer/main.go" -command="./bin/consumer" -polling=true -polling-interval=600
    ports:
      - "3001:3001"
    volumes:
      - "./:/app"